name: Build KivyMD APK (Native)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk python3-pip build-essential git unzip

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android-sdk
        PATH: ${{ env.PATH }}:${{ env.HOME }}/android-sdk/platform-tools:${{ env.HOME }}/android-sdk/cmdline-tools/latest/bin
      run: |
        buildozer android debug
