name: Build KivyMD App (No Docker Image)

on:
  push:
  pull_request:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean Buildozer cache
        run: rm -rf .buildozer

      - name: Install essential dependencies
        run: |
          python3 --version
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev \
          android-sdk google-android-platform-34-installer

      #- name: Accept Android licenses
      #  run: |
      #    yes | sudo sdkmanager --licenses

      - name: Install Buildozer in virtual environment
        run: |
          python3 -m venv ~/buildozer_venv
          source ~/buildozer_venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Configure and Build with Buildozer
        run: |
          source ~/buildozer_venv/bin/activate
          echo "Starting Buildozer build..."
          buildozer -v android debug

      - name: Find output APK
        id: find_apk
        run: |
          APK_FILE=$(find bin -name "*.apk" -print0 | xargs -0 ls -t | head -n 1)
          echo "filename=$APK_FILE" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.find_apk.outputs.filename }}
