name: Build KivyMD App (No Docker Image)

on:
  push:
  pull_request:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (OpenJDK 17 for Android build)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Buildozer dependencies
        run: |
          pwd
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          #sudo apt install -y git zip unzip autoconf libtool pkg-config build-essential \
           # python3 python3-dev python3-pip python3-setuptools python3-venv \
            #cython3 openjdk-17-jdk

      - name: Install Buildozer in a virtual environment
        run: |
          python3 -m venv ~/buildozer_venv
          source ~/buildozer_venv/bin/activate
          pip install --upgrade pip
          # Explicitly install setuptools first to provide distutils
          pip install setuptools
          pip install buildozer

      - name: Configure and Build with Buildozer
        working-directory: ./
        run: |
          source ~/buildozer_venv/bin/activate

          # --- IMPORTANT: Configure your buildozer.spec here ---
          # ... (keep your sed commands here as before) ...
          sed -i "s/^title = .*/title = My KivyMD App/" buildozer.spec
          sed -i "s/^package\.name = .*/package.name = myapp/" buildozer.spec
          sed -i "s/^package\.domain = .*/package.domain = com.example/" buildozer.spec
          sed -i "s/^requirements = .*/requirements = python3,kivy,kivymd,pillow/" buildozer.spec
          sed -i "s/^#android\.api = .*/android.api = 33/" buildozer.spec
          sed -i "s/^#android\.minapi = .*/android.minapi = 21/" buildozer.spec
          sed -i "s/^#android\.archs = .*/android.archs = arm64-v8a,armeabi-v7a/" buildozer.spec

          # Run the build
          buildozer android debug

      - name: Find output APK
        id: find_apk
        run: |
          APK_FILE=$(find bin -name "*.apk" -print0 | xargs -0 ls -t | head -n 1)
          echo "Found APK: $APK_FILE"
          echo "filename=$APK_FILE" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.find_apk.outputs.filename }}
