name: Build KivyMD APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip python3-setuptools \
          python3-wheel libffi-dev \
          libssl-dev build-essential \
          libsqlite3-dev libjpeg-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivymd-app-apk
        path: bin/*.apk
