name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git unzip openjdk-17-jdk python3-pip autoconf \
          libtool pkg-config zlib1g-dev libncurses5-dev \
          libtinfo5 cmake libssl-dev libffi-dev python3-dev

    - name: Install Buildozer and Cython
      run: |
        python -m pip install --upgrade pip setuptools
        pip install --user buildozer==1.5.0 cython==0.29.32

    - name: Run Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug <<<y
